{
	"name": "Yudha Stock Card",
	"version": "1.0",
	"depends": [
		"stock",
		'stock_account',
		'purchase_stock',
		'sale_management',
		'account_accountant'
	],
	"author": "Albertus Restiyanto Pramayudha",
	"website": "https://www.linkedin.com/in/albertus-restiyanto-pramayudha-470261a8/",
    'category': 'Warehouse',
	'price': '180',
    'currency': 'EUR',
	"summary" : "This modul to display stock card per product per Warehouse and product summary per Warehouse",
	"description": """  stock,
	                    stock card,
	                    stock card in odoo,
	                    stock card per location,
	                    stockcard,
	                    stock card per product,
			    stock card summary,
	                    product,
	                    product summary per warehouse,
			    reporting in odoo,
			    report product,
			    report product per warehouse,
			    summary product,
			    report summary product,
			    custome report,
			    custome report in odoo,
			    odoo report,
			    custume report,
			    custume report in odoo,
                      	    custume report,
                            custume report in odoo,
                            costume report,
                            costume report in odoo,
                            customize report,
                            customize report in odoo,			    
			    summary,
""",
	"data": [
		"views/yudha_stock_card_view.xml",
		'views/yudha_stock_card_summary_view.xml',
		'views/yudha_stock_card_menu.xml',
		'views/yudha_inv_valuation.xml',
		'views/yudha_inv_valuation_reports.xml',
		# 'views/yudha_valuation_warehouse.xml',
		'report/yudha_stock_card.xml',
		'report/yudha_stock_card_summary.xml',
		'security/ir.model.access.csv',
	],
	"application": True,
	"installable": True,
    'auto_install': False,
    "images": ["static/description/icon.png"],
}
